#!/usr/bin/python3

import sys
import math


def factorize(number):
    factors = []
    while number % 2 == 0:
        factors.append((2, number // 2))
        number //= 2
    for i in range(3, int(math.sqrt(number)) + 1, 2):
        while number % i == 0:
            factors.append((i, number // i))
            number //= i
    if number > 2:
        factors.append((number, 1))
    return factors


def main():
    file_path = sys.argv[1]
    with open(file_path, 'r') as file:
        factorizations = []
        for line in file:
            number = int(line.strip())
            factors = factorize(number)
            factorizations.append(f"{number}={factors[0][0]}*{factors[0][1]}")
        for factorization in factorizations:
            print(factorization)


if __name__ == '__main__':
    if len(sys.argv) != 2:
        print("Usage: python factors.py <file>")
        sys.exit(1)
    main()
