#!/usr/bin/python3

import sys


def factorize(number):
    """
    function to factorize number
    """
    factors = []
    for i in range(2, number):
        if number % i == 0:
            factors.append((i, number // i))
            break
    return factors


def main():
    """
    main function to read file and print factorization
    """
    file_path = sys.argv[1]
    with open(file_path, 'r') as file:
        factorizations = []
        for line in file:
            number = int(line.strip())
            factors = factorize(number)
            factorizations.append(f"{number}={factors[0][0]}*{factors[0][1]}")
        for factorization in factorizations:
            print(factorization)


if __name__ == '__main__':
    if len(sys.argv) != 2:
        print("Usage: python factors.py <file>")
        sys.exit(1)
    main()
