#!/usr/bin/python3

import sys


def is_prime(num):
    if num < 2:
        return False
    for i in range(2, int(num ** 0.5) + 1):
        if num % i == 0:
            return False
    return True


def factorize_number(number):
    factors = []
    for i in range(2, int(number ** 0.5) + 1):
        if number % i == 0:
            factors.append((i, number // i))
            break
    return factors


def main():
    if len(sys.argv) != 2:
        print("Usage: python rsa.py <file>")
        sys.exit(1)
    
    input_file = sys.argv[1]
    
    with open(input_file, 'r') as file:
        numbers = file.read().splitlines()
    
    for num in numbers:
        num = int(num)
        result = factorize_number(num)
        if result:
            for factor_pair in result:
                if is_prime(factor_pair[0]) and is_prime(factor_pair[1]):
                    print(f"{num}={factor_pair[0]}*{factor_pair[1]}")
                    break


if __name__ == '__main__':
    main()
